const langArr = {
    "general" :  {
        "ru": "Основные настройки",
        "en": "General setings",
        "ua": "Основні налаштування",
        "es": "Ajustes básicos",
        "zh": "基本设置",
        "hi": "मूल सेटिंग्स",
        "de": "Grundeinstellungen",
    }, 
    "qrsize": {
        "ru": "Размер кода",
        "en": "QR code size",
        "ua": "Розмір QR коду",
        "es": "Tamaño del código QR",
        "zh": "QR码大小",
        "hi": "क्यूआर कोड का आकार",
        "de": "QR-Code-Größe",
    }, 
    "qrsize2": {
        "ru": "Размер кода",
        "en": "QR code size",
        "ua": "Розмір QR коду",
        "es": "Tamaño del código QR",
        "zh": "QR码大小",
        "hi": "क्यूआर कोड का आकार",
        "de": "QR-Code-Größe",
    }, 
    "cl": {
        "ru": "Уровень корекции",
        "en": "Corection level",
        "ua": "Рівень корекції",
        "es": "Nivel de corrección",
        "zh": "校正水平",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Korrekturstufe",
    }, 
    "cl2": {
        "ru": "Уровень корекции",
        "en": "Corection level",
        "ua": "Рівень корекції",
        "es": "Nivel de corrección",
        "zh": "校正水平",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Korrekturstufe",
    }, 
    "about": {
        "ru": "О расширении",
        "en": "About extentions",
        "ua": "Про розширення",
        "es": "Sobre la expansión",
        "zh": "关于扩大",
        "hi": "विस्तार के बारे में",
        "de": "Über Expansion",
    },

    "qrsizeOpt1": {
        "ru": "400x400 пикселей",
        "en": "400x400 pixels",
        "ua": "400x400 пікселів",
        "es": "400x400 píxeles",
        "zh": "400x400像素",
        "hi": "400x400 पिक्सेल",
        "de": "400x400 pixel",
    },
    "qrsizeOpt2": {
        "ru": "300x300 пикселей",
        "en": "300x300 pixels",
        "ua": "300x300 пікселів",
        "es": "300x300 píxeles",
        "zh": "300x300像素",
        "hi": "300x300 पिक्सेल",
        "de": "300x300 pixel",
    },
    "qrsizeOpt3": {
        "ru": "250x250 пикселей",
        "en": "250x250 pixels",
        "ua": "250x250 пікселів",
        "es": "250x250 píxeles",
        "zh": "250x250像素",
        "hi": "250x250 पिक्सेल",
        "de": "250x250 pixel",
    },
    "qrsizeOpt4": {
        "ru": "200x200 пикселей",
        "en": "200x200 pixels",
        "ua": "200x200 пікселів",
        "es": "200x200 píxeles",
        "zh": "200x200像素",
        "hi": "200x200 पिक्सेल",
        "de": "200x200 pixel",
    },
    "clOpt1": {
        "ru": "Уровень H - до 30% урона",
        "en": "Level H - at 30% damage",
        "ua": "Рівень H - до 30% шкоди",
        "es": "Nivel H: hasta un 30% de daño",
        "zh": "H级-高达30％的伤害",
        "hi": "स्तर एच - नुकसान का 30% तक",
        "de": "Stufe H - bis zu 30% des Schadens",
    },
    "clOpt2": {
        "ru": "Уровень Q - до 25% урона",
        "en": "Level Q - at 25% damage",
        "ua": "Рівень Q - до 25% шкоди",
        "es": "Nivel Q: hasta un 25% de daño",
        "zh": "Q级-高达25％的伤害",
        "hi": "क्यू स्तर - 25% तक की क्षति",
        "de": "Stufe Q - bis zu 25% des Schadens",
    },
    "clOpt3": {
        "ru": "Уровень M - до 15% урона",
        "en": "Level M - at 15% damage",
        "ua": "Рівень M - до 15% шкоди",
        "es": "Nivel M: hasta un 15% de daño",
        "zh": "M级-高达15％的伤害",
        "hi": "स्तर एम - नुकसान का 15% तक",
        "de": "Stufe M - bis zu 15% des Schadens",
    },
    "clOpt4": {
        "ru": "Уровень L - до 7% урона",
        "en": "Level L - at 7% damage",
        "ua": "Рівень L - до 7% шкоди",
        "es": "Nivel L: hasta un 7% de daño",
        "zh": "L级-高达7％的伤害",
        "hi": "लेवल L - 7% तक की क्षति",
        "de": "Stufe L - bis zu 7% des Schadens",
    },


    "aeTile1": {
        "ru": "Возможности расширения",
        "en": "Possibilities of expansion",
        "ua": "Можливості розширення",
        "es": "Posibilidades de expansión",
        "zh": "扩张的可能性",
        "hi": "विस्तार की संभावनाएँ",
        "de": "Erweiterungsmöglichkeiten",
    },
    "aeSubTitle1": {
        "ru": "С помощью данного расширения вы можете:",
        "en": "With this extension you can:",
        "ua": "З допомогою даного розширення ви можете:",
        "es": "Con esta extensión puedes:",
        "zh": "使用此扩展程序，您可以：",
        "hi": "इस विस्तार के साथ आप कर सकते हैं:",
        "de": "Mit dieser Erweiterung können Sie:",
    },
    "aeUl1L1": {
        "ru": "создавать QR код со ссылкой на активную вкладку",
        "en": "create a QR code with a link to the active tab",
        "ua": "створювати QR код з посиланням на активну вкладку",
        "es": "crear un código QR con un enlace a la pestaña activa",
        "zh": "创建带有链接到浏览器中活动站点的QR码",
        "hi": "सक्रिय टैब के लिंक के साथ एक क्यूआर कोड बनाएं",
        "de": "Erstellen Sie einen QR-Code mit einem Link zur aktiven Registerkarte",
    },
    "aeUl1L2": {
        "ru": "изменять ссылки qr кода в реальном времени",
        "en": "change qr code links in real time",
        "ua": "змінювати посилання qr коду в реальному часі",
        "es": "cambiar enlaces de código en tiempo real",
        "zh": "实时更改代码链接",
        "hi": "वास्तविक समय में कोड लिंक बदलें",
        "de": "Code-Links in Echtzeit ändern",
    },
    "aeUl1L3": {
        "ru": "создавать qr код со своим текстом",
        "en": "create qr code with your text",
        "ua": "створювати qr код зі своїм текстом",
        "es": "crea código con tu texto",
        "zh": "创建代码，用自己的文字",
        "hi": "अपने स्वयं के पाठ के साथ कोड बनाने",
        "de": "Erstellen Sie Code mit Ihrem Text",
    },
    "aeUl1L4": {
        "ru": "загружать изображения с qr кодом",
        "en": "upload image with qr code",
        "ua": "завантажувати зображення з qr кодом",
        "es": "subir imagen con código",
        "zh": "用代码上传图像",
        "hi": "कोड के साथ छवि अपलोड करें",
        "de": "Bild mit Code hochladen",
    },
    "aeUl1L5": {
        "ru": "просматривать и управлять историей генерации",
        "en": "view and manage generation history",
        "ua": "переглядати та керувати історією генерації",
        "es": "ver y administrar el historial de generaciones",
        "zh": "查看和管理世代历史",
        "hi": "पीढ़ी के इतिहास को देखें और प्रबंधित करें",
        "de": "Generierungsverlauf anzeigen und verwalten",
    },
    "aeSubTitle2": {
        "ru": "Доступные настройки:",
        "en": "Available settings:",
        "ua": "Доступні налаштування:",
        "es": "Configuraciones disponibles:",
        "zh": "可用设置：",
        "hi": "उपलब्ध सेटिंग्स:",
        "de": "Verfügbare Einstellungen:",
    },
    "aeUl2L1": {
        "ru": "Размер окна и qr кода",
        "en": "window and qr code size",
        "ua": "pозмір вікна та qr коду",
        "es": "tamaño de ventana y código",
        "zh": "窗口和代码大小",
        "hi": "खिड़की और कोड का आकार",
        "de": "Fenster- und Codegröße",
    },
    "aeUl2L2": {
        "ru": "уровень коррекции ошибок",
        "en": "error correction level",
        "ua": "pівень корекції помилок",
        "es": "el nivel de corrección de errores",
        "zh": "纠错等级",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Fehlerkorrekturstufe",
    },
    "aeUl2L3": {
        "ru": "изменение языка",
        "en": "change of language",
        "ua": "зміна мови",
        "es": "cambio de idioma",
        "zh": "语言改变",
        "hi": "भाषा का परिवर्तन",
        "de": "Sprachwechsel",
    },
    "aeUl2L4": {
        "ru": "изменение цветовой гаммы",
        "en": "change the color scheme",
        "ua": "зміна кольорової гами",
        "es": "el nivel de corrección de errores",
        "zh": "改变配色方案",
        "hi": "रंग योजना बदलें",
        "de": "Ändern Sie das Farbschema",
    },
    "aeSubTitle3": {
        "ru": "Использование:",
        "en": "Using:",
        "ua": "Використання:",
        "es": "El uso de:",
        "zh": "使用方法：",
        "hi": "का उपयोग कर:",
        "de": "Verwenden von:",
    },

    "aeUl3L1": {
        "ru": "Возьмите мобильный телефон с камерой",
        "en": "Take a cell phone with a camera",
        "ua": "Візьміть мобільний телефон з камерою",
        "es": "Lleva un celular con cámara",
        "zh": "就拿手机带摄像头",
        "hi": "एक कैमरा के साथ एक स्मार्टफोन ले लो",
        "de": "Nehmen Sie ein Smartphone mit einer Kamera",
    },
    "aeUl3L2": {
        "ru": "Запустите программу для сканирования или камеру",
        "en": "Run a scanning program or camera",
        "ua": "Запустіть програму для сканування або камеру",
        "es": "Ejecute un programa de escaneo o una cámara",
        "zh": "运行一个扫描程序或相机",
        "hi": "स्कैनिंग प्रोग्राम या कैमरा चलाएं",
        "de": "Führen Sie ein Scanprogramm oder eine Kamera aus",
    },
    "aeUl3L3": {
        "ru": "Наведите объектив камеры на qr код",
        "en": "Point the camera lens at the qr code",
        "ua": "Наведіть об'єктив камери на qr код",
        "es": "Apunta la lente de la cámara al código",
        "zh": "将相机镜头对准代码",
        "hi": "कोड पर कैमरा लेंस का लक्ष्य रखें",
        "de": "Richten Sie das Kameraobjektiv auf den Code",
    },
    "aeUl3L4": {
        "ru": "Получите информацию!",
        "en": "Get information!",
        "ua": "Отримайте інформацію!",
        "es": "¡Obtener información!",
        "zh": "获取信息！",
        "hi": "जानकारी लो!",
        "de": "Informationen bekommen!",
    },

    "aeSubTitle4": {
        "ru": "Что такое QR код",
        "en": "What is a QR code",
        "ua": "Що таке QR код",
        "es": "¿Qué es un código QR",
        "zh": "什么是QR码",
        "hi": "एक क्यूआर कोड क्या है",
        "de": "Was ist ein QR-Code",
    },
    "aeText1": {
        "ru": "QR код «QR - Quick Response - Быстрый Отклик» - это двухмерный штрих-код (бар-код), предоставляющий информацию для быстрого ее распознавания с помощью камеры на мобильном телефоне. С помощью QR-кода можно закодировать любую информацию, например: текст, номер телефона, ссылку на сайт, изображения, визитную карточку и тому подобное.",
        "en": "QR code «QR - Quick Response - Quick Response» is a two-dimensional bar code (bar code), which provides information for quick recognition using a camera on a mobile phone. With the help of QR-code you can encode any information, for example: text, phone number, link to the site, image, business card, etc.",
        "ua": "QR код «QR - Quick Response - Швидкий Відгук» - це двомірний штрих-код (бар-код), що надає інформацію для швидкого її розпізнавання за допомогою камери на мобільному телефоні. За допомогою QR-коду можна закодувати будь-яку інформацію, наприклад: текст, номер телефону, посилання на сайт, зображення, візитну картку, тощо.",
        "es": "El código QR «QR - Quick Response - Quick Response» es un código de barras bidimensional (código de barras), que proporciona información para un reconocimiento rápido utilizando una cámara en un teléfono móvil. Con la ayuda del código QR puede codificar cualquier información, por ejemplo: texto, número de teléfono, enlace al sitio, imagen, tarjeta de visita, etc.",
        "zh": "QR码“ QR-快速响应-快速响应”是二维条形码（条形码），它提供了使用手机上的相机进行快速识别的信息。 随着QR码的帮助下，你可以在任何信息进行编码，例如：文本，电话号码，网站链接，图像，名片等。",
        "hi": "QR कोड «QR - त्वरित प्रतिक्रिया - त्वरित प्रतिक्रिया» एक दो आयामी बार कोड (बार कोड) है, जो एक मोबाइल फोन पर एक कैमरे का उपयोग कर त्वरित मान्यता के लिए जानकारी प्रदान करता है। क्यूआर-कोड की मदद से आप किसी भी जानकारी को एनकोड कर सकते हैं, उदाहरण के लिए: टेक्स्ट, फोन नंबर, साइट का लिंक, इमेज, बिजनेस कार्ड, आदि।",
        "de": "QR-Code «QR - Quick Response - Quick Response» ist ein zweidimensionaler Barcode (Barcode), der Informationen zur schnellen Erkennung mit einer Kamera auf einem Mobiltelefon bereitstellt. Mit Hilfe des QR-Codes können Sie alle Informationen verschlüsseln, zum Beispiel: Text, Telefonnummer, Site-Link, Bild, Visitenkarte usw.",
    },
    "aeText2": {
        "ru": "В отличие от старого штрих-кода, который сканируют тонким лучом, QR-код определяется сенсором как двумерное изображение. Три квадрата в углах изображения и меньшие синхронизувальни квадратики по всему кода позволяют нормализовать размер изображения и его ориентацию, а также угол, под которым сенсор расположен к поверхности изображения. Точки переводятся в двоичные числа с проверкой контрольных сумм. <br><br>Основное преимущество QR-кода - это легкое распознавание сканирующим оборудованием (в том числе и фотокамерой мобильного телефона). Хотя термин «QR code» является зарегистрированным товарным знаком «DENSO Corporation», использование кодов не облагается никакими лицензионными отчислениями, а сами они описаны и опубликованы в качестве стандартов ISO. Спецификация QR-кода не описывает формат данных.",
        "en": "Unlike the old barcode, which is scanned with a thin beam, the QR code is defined by the sensor as a two-dimensional image. Three squares in the corners of the image and smaller synchronization squares around the code allow you to normalize the size of the image and its orientation, as well as the angle at which the sensor is located to the surface of the image. Points are converted to binary numbers with checksums. <br><br>The main advantage of the QR-code is easy recognition by scanning equipment (including a mobile phone camera). Although the term \"QR code\" is a registered trademark of \"DENSO Corporation\", the use of codes is not subject to any license fees, and they themselves are described and published as ISO standards. The QR code specification does not describe the data format.",
        "ua": "На відміну від старого штрих-коду, який сканують тонким променем, QR-код визначається сенсором як двовимірне зображення. Три квадрати в кутах зображення та менші синхронізувальні квадратики по всьому коду дозволяють нормалізувати розмір зображення і його орієнтацію, а також кут, під яким сенсор розташований до поверхні зображення. Точки переводяться в двійкові числа з перевіркою контрольних сум. <br><br>Основна перевага QR-коду — це легке розпізнавання сканувальним обладнанням (в тому числі і фотокамерою мобільного телефону). Хоча термін «QR code» є зареєстрованим товарним знаком «DENSO Corporation», використання кодів не обкладається ніякими ліцензійними відрахуваннями, а самі вони описані й опубліковані як стандарти ISO. Специфікація QR-коду не описує формат даних.",
        "es": "A diferencia del antiguo código de barras, que se escanea con un haz delgado, el código QR lo define el sensor como una imagen bidimensional. Tres cuadrados en las esquinas de la imagen y cuadrados de sincronización más pequeños alrededor del código le permiten normalizar el tamaño de la imagen y su orientación, así como el ángulo en el que se ubica el sensor con la superficie de la imagen. <br><br>Los puntos se convierten en números binarios con sumas de comprobación. La principal ventaja del código QR es su fácil reconocimiento mediante el equipo de escaneo (incluida la cámara de un teléfono móvil). Aunque el término \"código QR\" es una marca registrada de \"DENSO Corporation\", el uso de códigos no está sujeto a tarifas de licencia, y ellos mismos se describen y publican como normas ISO. La especificación del código QR no describe el formato de los datos.",
        "zh": "与用细光束扫描的旧条形码不同，QR码由传感器定义为二维图像。 图像角落的三个正方形和代码周围的较小同步正方形使您可以标准化图像的大小及其方向，以及传感器与图像表面的夹角。 点数将转换为带有校验和的二进制数。 QR码的主要优点是易于通过扫描设备（包括手机摄像头）识别。 尽管“ QR代码”一词是“ DENSO Corporation”的注册商标，但是使用代码无需缴纳任何许可费用，它们本身已被描述并作为ISO标准发布。 QR码规范未描述数据格式。",
        "hi": "पुराने बारकोड के विपरीत, जो एक पतली बीम से स्कैन किया जाता है, क्यूआर कोड को सेंसर द्वारा दो-आयामी छवि के रूप में परिभाषित किया जाता है। छवि के कोनों में तीन वर्ग और कोड के चारों ओर छोटे सिंक्रनाइज़ेशन वर्ग आपको छवि के आकार और इसके अभिविन्यास को सामान्य करने की अनुमति देते हैं, साथ ही साथ कोण जिस पर सेंसर छवि की सतह पर स्थित है। अंक चेकसम के साथ बाइनरी नंबर में बदल जाते हैं। क्यूआर-कोड का मुख्य लाभ उपकरण (एक मोबाइल फोन कैमरा सहित) स्कैन करके आसान मान्यता है। यद्यपि \"QR कोड\" शब्द \"DENSO Corporation\" का एक पंजीकृत ट्रेडमार्क है, कोड का उपयोग किसी भी लाइसेंस शुल्क के अधीन नहीं है, और वे स्वयं आईएसओ मानकों के रूप में वर्णित और प्रकाशित किए जाते हैं। क्यूआर कोड विनिर्देश डेटा प्रारूप का वर्णन नहीं करता है।",
        "de": "Im Gegensatz zum alten Barcode, der mit einem dünnen Strahl gescannt wird, wird der QR-Code vom Sensor als zweidimensionales Bild definiert. Mit drei Quadraten in den Bildecken und kleineren Synchronisationsquadraten um den Code können Sie die Größe des Bildes und seine Ausrichtung sowie den Winkel, in dem sich der Sensor zur Oberfläche des Bildes befindet, normalisieren. Punkte werden mit Prüfsummen in Binärzahlen umgewandelt. <br><br>Der Hauptvorteil des QR-Codes ist die einfache Erkennung durch Scan-Geräte (einschließlich einer Handykamera). Obwohl der Begriff \"QR-Code\" eine eingetragene Marke der \"DENSO Corporation\" ist, fallen für die Verwendung von Codes keine Lizenzgebühren an, und sie selbst werden als ISO-Standards beschrieben und veröffentlicht. Die QR-Code-Spezifikation beschreibt das Datenformat nicht.",
    },
    "privacy": {
        "ru": "Политика конфиденциальности",
        "en": "Privacy Policy",
        "ua": "Політика конфіденційності",
        "es": "Política de privacidad",
        "zh": "隐私政策",
        "hi": "गोपनीयता नीति",
        "de": "Datenschutz-Bestimmungen",
    },
    "terms": {
        "ru": "Условия использования",
        "en": "Terms of Services",
        "ua": "Умови використання",
        "es": "Términos de servicio",
        "zh": "服务期限",
        "hi": "सेवा की अवधि",
        "de": "Länge der Dienstzeit",
    },
    "developer": {
        "ru": "Разработчик",
        "en": "Developer",
        "ua": "Розробник",
        "es": "Desarrollador",
        "zh": "开发者",
        "hi": "डेवलपर",
        "de": "Entwickler",
    },
    "def1": {
        "ru": "По умолчанию",
        "en": "Default",
        "ua": "За замовчуванням",
        "es": "Defecto",
        "zh": "缺省",
        "hi": "चूक",
        "de": "Standard",
    },
    "def2": {
        "ru": "По умолчанию",
        "en": "Default",
        "ua": "За замовчуванням",
        "es": "Defecto",
        "zh": "缺省",
        "hi": "चूक",
        "de": "Standard",
    },

    "settingMessage": {
        "ru": "111",
        "en": "111",
        "ua": "111",
        "es": "111",
        "zh": "111",
        "hi": "111",
        "de": "111",
    },

    "themeWtite": {
        "ru": "Светлая",
        "en": "Light",
        "ua": "Світла",
        "es": "Ligera",
        "zh": "光",
        "hi": "रोशनी",
        "de": "Licht",
    },
    "themeBlack": {
        "ru": "Темная",
        "en": "Dark",
        "ua": "Темна",
        "es": "Oscura",
        "zh": "黑",
        "hi": "अंधेरा",
        "de": "Dunkel",
    },
    "themeBlue": {
        "ru": "Синяя",
        "en": "Blue",
        "ua": "Синя",
        "es": "Azul",
        "zh": "蓝色",
        "hi": "नीला",
        "de": "Blau",
    },
    "hist-title": {
        "ru": "История просмотров",
        "en": "History",
        "ua": "Історія переглядів",
        "es": "Historia",
        "zh": "历史",
        "hi": "इतिहास",
        "de": "Geschichte",
    },
    "hist-btn": {
        "ru": "Загрузить историю",
        "en": "Show history",
        "ua": "Завантажити історію",
        "es": "Mostrar la historia",
        "zh": "显示历史",
        "hi": "इतिहास दिखाओ",
        "de": "Zeige die Geschichte",
    },
    "history-btn": {
        "ru": "История",
        "en": "History",
        "ua": "Історія",
        "es": "Historia",
        "zh": "历史",
        "hi": "इतिहास",
        "de": "Geschichte",
    },
    "search-text": {
        "ru": "Поиск",
        "en": "Search",
        "ua": "Пошук",
        "es": "Búsqueda",
        "zh": "搜索",
        "hi": "खोज",
        "de": "Suche",
    },




    "codesize_about__about": {
        "ru": "О настройке размера",
        "en": "About size settings",
        "ua": "Про налаштування розміру",
        "es": "Acerca de la configuración de tamaño",
        "zh": "关于尺寸设置",
        "hi": "आकार सेटिंग्स के बारे में",
        "de": "Informationen zu Größeneinstellungen",
    },
    "codesize_about__p": {
        "ru": "Размер всплывающего окна расширения и размер QR кода в пикселях",
        "en": "The size of the extension pop-up window and the size of the QR code in pixels",
        "ua": "Розмір спливаючого вікна розширення та розмір QR коду в пікселях",
        "es": "El tamaño de la ventana emergente de la extensión y el tamaño del código QR en píxeles",
        "zh": "扩展名弹出窗口的大小和QR码的大小（以像素为单位）",
        "hi": "विस्तार पॉप-अप विंडो के आकार और पिक्सेल में QR कोड का आकार",
        "de": "Die Größe des Erweiterungs-Popup-Fensters und die Größe des QR-Codes in Pixel",
    },
    "corection_about__about": {
        "ru": "Что такое уровень коррекции",
        "en": "What is the level of correction",
        "ua": "Що таке рівень корекції",
        "es": "¿Cuál es el nivel de corrección?",
        "zh": "什么是矫正水平",
        "hi": "सुधार का स्तर क्या है",
        "de": "Was ist das Niveau der Korrektur",
    },
    "corection_about__p1": {
        "ru": "Стандарт QR-кода позволяет выбрать 4 различных уровня восстановления ошибок от следующего количества повреждений:",
        "en": "The QR code standard allows you to select 4 different levels of error recovery from the following damage:",
        "ua": "Стандарт QR-коду дозволяє вибрати 4 різних рівня відновлення помилок від наступної кількості пошкоджень:",
        "es": "El estándar de código QR le permite seleccionar 4 niveles diferentes de recuperación de errores de los siguientes daños:",
        "zh": "QR码标准可让您从以下损坏中选择4种不同级别的错误恢复：",
        "hi": "QR कोड मानक आप निम्नलिखित नुकसान से त्रुटि वसूली के 4 विभिन्न स्तरों को चुनने के लिए अनुमति देता है:",
        "de": "Mit dem QR-Code-Standard können Sie 4 verschiedene Stufen der Fehlerbehebung aus folgenden Schäden auswählen:",
    },
    "corection_about__ul1li1": {
        "ru": "L: 7% емкости для коррекции.",
        "en": "L: 7% capacity for correction.",
        "ua": "L: 7% ємності для корекції.",
        "es": "L: 7% de capacidad de corrección.",
        "zh": "L：7％的校正能力。",
        "hi": "एल: सुधार के लिए 7% क्षमता।",
        "de": "L: 7% der Kapazität zur Korrektur.",
    },
    "corection_about__ul1li2": {
        "ru": "M: 15% емкости для коррекции.",
        "en": "M: 15% capacity for correction.",
        "ua": "M: 15% ємності для корекції.",
        "es": "M: 15% de capacidad de corrección.",
        "zh": "M：15％的校正能力。",
        "hi": "एम: सुधार के लिए 15% क्षमता।",
        "de": "M: 15% der Kapazität für die Korrektur.",
    },
    "corection_about__ul1li3": {
        "ru": "Q: 25% емкости для коррекции.",
        "en": "Q: 25% capacity for correction.",
        "ua": "Q: 25% ємності для корекції.",
        "es": "Q: 25% de capacidad de corrección.",
        "zh": "Q：25％的校正能力。",
        "hi": "प्रश्न: सुधार के लिए 25% क्षमता।",
        "de": "Q: 25% der Kapazität für die Korrektur.",
    },
    "corection_about__ul1li4": {
        "ru": "H: 30% емкости для коррекции.",
        "en": "H: 30% capacity for correction.",
        "ua": "H: 30% ємності для корекції.",
        "es": "H: 30% de capacidad de corrección.",
        "zh": "H：30％的校正能力。",
        "hi": "एच: सुधार के लिए 30% क्षमता।",
        "de": "H: 30% der Kapazität für die Korrektur.",
    },
    "corection_about__p2": {
        "ru": "В QR-коде реализована коррекция ошибок для возможного восстановления частично поврежденных знаков.",
        "en": "The QR code implements error correction for possible recovery of partially damaged characters.",
        "ua": "В QR-коді реалізована корекція помилок для можливого відновлення частково пошкоджених знаків.",
        "es": "El código QR implementa la corrección de errores para una posible recuperación de caracteres parcialmente dañados.",
        "zh": "QR码执行错误纠正，以恢复部分损坏的字符。",
        "hi": "क्यूआर कोड आंशिक रूप से क्षतिग्रस्त पात्रों की संभावित वसूली के लिए त्रुटि सुधार को लागू करता है।",
        "de": "Der QR-Code implementiert eine Fehlerkorrektur zur möglichen Wiederherstellung teilweise beschädigter Zeichen.",
    },
    "corection_about__p3": {
        "ru": "Чем выше уровень коррекции ошибок, тем большего размера символ нужен для кодирования того же объема данных.",
        "en": "The higher the error correction level, the larger the character required to encode the same amount of data.",
        "ua": "Чим вище рівень корекції помилок, тим більшого розміру символ потрібнен для кодування того ж обсягу даних.",
        "es": "Cuanto mayor sea el nivel de corrección de errores, mayor será el tamaño del símbolo necesario para codificar la misma cantidad de datos.",
        "zh": "纠错级别越高，对相同数据量进行编码所需的字符越大。",
        "hi": "त्रुटि सुधार स्तर जितना अधिक होता है, उतना ही बड़ा चरित्र डेटा की समान मात्रा को एनकोड करने के लिए आवश्यक होता है।",
        "de": "Je höher die Fehlerkorrekturstufe ist, desto größer ist das Zeichen, das zum Codieren derselben Datenmenge erforderlich ist.",
    },
    "corection_about__examp": {
        "ru": "Наглядный пример",
        "en": "Illustrative example",
        "ua": "Наглядний приклад",
        "es": "Ejemplo ilustrativo",
        "zh": "说明性的例子",
        "hi": "व्याख्यात्मक उदाहरण",
        "de": "Bildhaftes Beispiel",
    },
    "0": {
        "ru": "",
        "en": "",
        "ua": "",
        "es": "",
        "zh": "",
        "hi": "",
        "de": "",
    }
};