const langArr = {
    "general" :  {
        "ru": "Основные настройки",
        "en": "General setings",
        "ua": "Основні налаштування",
        "es": "Ajustes básicos",
        "zh": "基本设置",
        "hi": "मूल सेटिंग्स",
        "de": "Grundeinstellungen",
    }, 
    "qrsize": {
        "ru": "Размер кода",
        "en": "QR code size",
        "ua": "Розмір QR коду",
        "es": "Tamaño del código QR",
        "zh": "QR码大小",
        "hi": "क्यूआर कोड का आकार",
        "de": "QR-Code-Größe",
    }, 
    "qrsize2": {
        "ru": "Размер кода",
        "en": "QR code size",
        "ua": "Розмір QR коду",
        "es": "Tamaño del código QR",
        "zh": "QR码大小",
        "hi": "क्यूआर कोड का आकार",
        "de": "QR-Code-Größe",
    }, 
    "cl": {
        "ru": "Уровень корекции",
        "en": "Corection level",
        "ua": "Рівень корекції",
        "es": "Nivel de corrección",
        "zh": "校正水平",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Korrekturstufe",
    }, 
    "cl2": {
        "ru": "Уровень корекции",
        "en": "Corection level",
        "ua": "Рівень корекції",
        "es": "Nivel de corrección",
        "zh": "校正水平",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Korrekturstufe",
    }, 
    "about": {
        "ru": "О расширении",
        "en": "About extentions",
        "ua": "Про розширення",
        "es": "Sobre la expansión",
        "zh": "关于扩大",
        "hi": "विस्तार के बारे में",
        "de": "Über Expansion",
    },

    "qrsizeOpt1": {
        "ru": "400x400 пикселей",
        "en": "400x400 pixels",
        "ua": "400x400 пікселів",
        "es": "400x400 píxeles",
        "zh": "400x400像素",
        "hi": "400x400 पिक्सेल",
        "de": "400x400 pixel",
    },
    "qrsizeOpt2": {
        "ru": "300x300 пикселей",
        "en": "300x300 pixels",
        "ua": "300x300 пікселів",
        "es": "300x300 píxeles",
        "zh": "300x300像素",
        "hi": "300x300 पिक्सेल",
        "de": "300x300 pixel",
    },
    "qrsizeOpt3": {
        "ru": "250x250 пикселей",
        "en": "250x250 pixels",
        "ua": "250x250 пікселів",
        "es": "250x250 píxeles",
        "zh": "250x250像素",
        "hi": "250x250 पिक्सेल",
        "de": "250x250 pixel",
    },
    "qrsizeOpt4": {
        "ru": "200x200 пикселей",
        "en": "200x200 pixels",
        "ua": "200x200 пікселів",
        "es": "200x200 píxeles",
        "zh": "200x200像素",
        "hi": "200x200 पिक्सेल",
        "de": "200x200 pixel",
    },
    "clOpt1": {
        "ru": "Уровень H - до 30% урона",
        "en": "Level H - at 30% damage",
        "ua": "Рівень H - до 30% шкоди",
        "es": "Nivel H: hasta un 30% de daño",
        "zh": "H级-高达30％的伤害",
        "hi": "स्तर एच - नुकसान का 30% तक",
        "de": "Stufe H - bis zu 30% des Schadens",
    },
    "clOpt2": {
        "ru": "Уровень Q - до 25% урона",
        "en": "Level Q - at 25% damage",
        "ua": "Рівень Q - до 25% шкоди",
        "es": "Nivel Q: hasta un 25% de daño",
        "zh": "Q级-高达25％的伤害",
        "hi": "क्यू स्तर - 25% तक की क्षति",
        "de": "Stufe Q - bis zu 25% des Schadens",
    },
    "clOpt3": {
        "ru": "Уровень M - до 15% урона",
        "en": "Level M - at 15% damage",
        "ua": "Рівень M - до 15% шкоди",
        "es": "Nivel M: hasta un 15% de daño",
        "zh": "M级-高达15％的伤害",
        "hi": "स्तर एम - नुकसान का 15% तक",
        "de": "Stufe M - bis zu 15% des Schadens",
    },
    "clOpt4": {
        "ru": "Уровень L - до 7% урона",
        "en": "Level L - at 7% damage",
        "ua": "Рівень L - до 7% шкоди",
        "es": "Nivel L: hasta un 7% de daño",
        "zh": "L级-高达7％的伤害",
        "hi": "लेवल L - 7% तक की क्षति",
        "de": "Stufe L - bis zu 7% des Schadens",
    },


    "aeTile1": {
        "ru": "Возможности расширения",
        "en": "Possibilities of expansion",
        "ua": "Можливості розширення",
        "es": "Posibilidades de expansión",
        "zh": "扩张的可能性",
        "hi": "विस्तार की संभावनाएँ",
        "de": "Erweiterungsmöglichkeiten",
    },
    "aeSubTitle1": {
        "ru": "С помощью данного расширения вы можете:",
        "en": "With this extension you can:",
        "ua": "З допомогою даного розширення ви можете:",
        "es": "Con esta extensión puedes:",
        "zh": "使用此扩展程序，您可以：",
        "hi": "इस विस्तार के साथ आप कर सकते हैं:",
        "de": "Mit dieser Erweiterung können Sie:",
    },
    "aeUl1L1": {
        "ru": "создавать QR код со ссылкой на активную вкладку",
        "en": "create a QR code with a link to the active tab",
        "ua": "створювати QR код з посиланням на активну вкладку",
        "es": "crear un código QR con un enlace a la pestaña activa",
        "zh": "创建带有链接到浏览器中活动站点的QR码",
        "hi": "सक्रिय टैब के लिंक के साथ एक क्यूआर कोड बनाएं",
        "de": "Erstellen Sie einen QR-Code mit einem Link zur aktiven Registerkarte",
    },
    "aeUl1L2": {
        "ru": "изменять ссылки qr кода в реальном времени",
        "en": "change qr code links in real time",
        "ua": "змінювати посилання qr коду в реальному часі",
        "es": "cambiar enlaces de código en tiempo real",
        "zh": "实时更改代码链接",
        "hi": "वास्तविक समय में कोड लिंक बदलें",
        "de": "Code-Links in Echtzeit ändern",
    },
    "aeUl1L3": {
        "ru": "создавать qr код со своим текстом",
        "en": "create qr code with your text",
        "ua": "створювати qr код зі своїм текстом",
        "es": "crea código con tu texto",
        "zh": "创建代码，用自己的文字",
        "hi": "अपने स्वयं के पाठ के साथ कोड बनाने",
        "de": "Erstellen Sie Code mit Ihrem Text",
    },
    "aeUl1L4": {
        "ru": "загружать изображения с qr кодом",
        "en": "upload image with qr code",
        "ua": "завантажувати зображення з qr кодом",
        "es": "subir imagen con código",
        "zh": "用代码上传图像",
        "hi": "कोड के साथ छवि अपलोड करें",
        "de": "Bild mit Code hochladen",
    },
    "aeSubTitle2": {
        "ru": "Доступные настройки:",
        "en": "Available settings:",
        "ua": "Доступні налаштування:",
        "es": "Configuraciones disponibles:",
        "zh": "可用设置：",
        "hi": "उपलब्ध सेटिंग्स:",
        "de": "Verfügbare Einstellungen:",
    },
    "aeUl2L1": {
        "ru": "Размер окна и qr кода",
        "en": "window and qr code size",
        "ua": "pозмір вікна та qr коду",
        "es": "tamaño de ventana y código",
        "zh": "窗口和代码大小",
        "hi": "खिड़की और कोड का आकार",
        "de": "Fenster- und Codegröße",
    },
    "aeUl2L2": {
        "ru": "уровень коррекции ошибок",
        "en": "error correction level",
        "ua": "pівень корекції помилок",
        "es": "el nivel de corrección de errores",
        "zh": "纠错等级",
        "hi": "त्रुटि सुधार स्तर",
        "de": "Fehlerkorrekturstufe",
    },
    "aeSubTitle3": {
        "ru": "Использование:",
        "en": "Using:",
        "ua": "Використання:",
        "es": "El uso de:",
        "zh": "使用方法：",
        "hi": "का उपयोग कर:",
        "de": "Verwenden von:",
    },

    "aeUl3L1": {
        "ru": "Возьмите мобильный телефон с камерой",
        "en": "Take a cell phone with a camera",
        "ua": "Візьміть мобільний телефон з камерою",
        "es": "Lleva un celular con cámara",
        "zh": "就拿手机带摄像头",
        "hi": "एक कैमरा के साथ एक स्मार्टफोन ले लो",
        "de": "Nehmen Sie ein Smartphone mit einer Kamera",
    },
    "aeUl3L2": {
        "ru": "Запустите программу для сканирования или камеру",
        "en": "Run a scanning program or camera",
        "ua": "Запустіть програму для сканування або камеру",
        "es": "Ejecute un programa de escaneo o una cámara",
        "zh": "运行一个扫描程序或相机",
        "hi": "स्कैनिंग प्रोग्राम या कैमरा चलाएं",
        "de": "Führen Sie ein Scanprogramm oder eine Kamera aus",
    },
    "aeUl3L3": {
        "ru": "Наведите объектив камеры на qr код",
        "en": "Point the camera lens at the qr code",
        "ua": "Наведіть об'єктив камери на qr код",
        "es": "Apunta la lente de la cámara al código",
        "zh": "将相机镜头对准代码",
        "hi": "कोड पर कैमरा लेंस का लक्ष्य रखें",
        "de": "Richten Sie das Kameraobjektiv auf den Code",
    },
    "aeUl3L4": {
        "ru": "Получите информацию!",
        "en": "Get information!",
        "ua": "Отримайте інформацію!",
        "es": "¡Obtener información!",
        "zh": "获取信息！",
        "hi": "जानकारी लो!",
        "de": "Informationen bekommen!",
    },

    "aeSubTitle4": {
        "ru": "Что такое QR код",
        "en": "What is a QR code",
        "ua": "Що таке QR код",
        "es": "¿Qué es un código QR",
        "zh": "什么是QR码",
        "hi": "एक क्यूआर कोड क्या है",
        "de": "Was ist ein QR-Code",
    },
    "aeText1": {
        "ru": "QR код «QR - Quick Response - Быстрый Отклик» - это двухмерный штрих-код (бар-код), предоставляющий информацию для быстрого ее распознавания с помощью камеры на мобильном телефоне. С помощью QR-кода можно закодировать любую информацию, например: текст, номер телефона, ссылку на сайт, изображения, визитную карточку и тому подобное.",
        "en": "QR code «QR - Quick Response - Quick Response» is a two-dimensional bar code (bar code), which provides information for quick recognition using a camera on a mobile phone. With the help of QR-code you can encode any information, for example: text, phone number, link to the site, image, business card, etc.",
        "ua": "QR код «QR - Quick Response - Швидкий Відгук» - це двомірний штрих-код (бар-код), що надає інформацію для швидкого її розпізнавання за допомогою камери на мобільному телефоні. За допомогою QR-коду можна закодувати будь-яку інформацію, наприклад: текст, номер телефону, посилання на сайт, зображення, візитну картку, тощо.",
        "es": "El código QR «QR - Quick Response - Quick Response» es un código de barras bidimensional (código de barras), que proporciona información para un reconocimiento rápido utilizando una cámara en un teléfono móvil. Con la ayuda del código QR puede codificar cualquier información, por ejemplo: texto, número de teléfono, enlace al sitio, imagen, tarjeta de visita, etc.",
        "zh": "QR码“ QR-快速响应-快速响应”是二维条形码（条形码），它提供了使用手机上的相机进行快速识别的信息。 随着QR码的帮助下，你可以在任何信息进行编码，例如：文本，电话号码，网站链接，图像，名片等。",
        "hi": "QR कोड «QR - त्वरित प्रतिक्रिया - त्वरित प्रतिक्रिया» एक दो आयामी बार कोड (बार कोड) है, जो एक मोबाइल फोन पर एक कैमरे का उपयोग कर त्वरित मान्यता के लिए जानकारी प्रदान करता है। क्यूआर-कोड की मदद से आप किसी भी जानकारी को एनकोड कर सकते हैं, उदाहरण के लिए: टेक्स्ट, फोन नंबर, साइट का लिंक, इमेज, बिजनेस कार्ड, आदि।",
        "de": "QR-Code «QR - Quick Response - Quick Response» ist ein zweidimensionaler Barcode (Barcode), der Informationen zur schnellen Erkennung mit einer Kamera auf einem Mobiltelefon bereitstellt. Mit Hilfe des QR-Codes können Sie alle Informationen verschlüsseln, zum Beispiel: Text, Telefonnummer, Site-Link, Bild, Visitenkarte usw.",
    },
    "privacy": {
        "ru": "Политика конфиденциальности",
        "en": "Privacy Policy",
        "ua": "Політика конфіденційності",
        "es": "Política de privacidad",
        "zh": "隐私政策",
        "hi": "गोपनीयता नीति",
        "de": "Datenschutz-Bestimmungen",
    },
    "terms": {
        "ru": "Условия использования",
        "en": "Terms of Services",
        "ua": "Умови використання",
        "es": "Términos de servicio",
        "zh": "服务期限",
        "hi": "सेवा की अवधि",
        "de": "Länge der Dienstzeit",
    },
    "developer": {
        "ru": "Разработчик",
        "en": "Developer",
        "ua": "Розробник",
        "es": "Desarrollador",
        "zh": "开发者",
        "hi": "डेवलपर",
        "de": "Entwickler",
    },
    "def1": {
        "ru": "По умолчанию",
        "en": "Default",
        "ua": "За замовчуванням",
        "es": "Defecto",
        "zh": "缺省",
        "hi": "चूक",
        "de": "Standard",
    },
    "def2": {
        "ru": "По умолчанию",
        "en": "Default",
        "ua": "За замовчуванням",
        "es": "Defecto",
        "zh": "缺省",
        "hi": "चूक",
        "de": "Standard",
    },

    "settingMessage": {
        "ru": "111",
        "en": "111",
        "ua": "111",
        "es": "111",
        "zh": "111",
        "hi": "111",
        "de": "111",
    },

    "themeWtite": {
        "ru": "Светлая",
        "en": "Light",
        "ua": "Світла",
        "es": "Ligera",
        "zh": "光",
        "hi": "रोशनी",
        "de": "Licht",
    },
    "themeBlack": {
        "ru": "Темная",
        "en": "Dark",
        "ua": "Темна",
        "es": "Oscura",
        "zh": "黑",
        "hi": "अंधेरा",
        "de": "Dunkel",
    },
    "themeBlue": {
        "ru": "Синяя",
        "en": "Blue",
        "ua": "Синя",
        "es": "Azul",
        "zh": "蓝色",
        "hi": "नीला",
        "de": "Blau",
    },
    "hist-title": {
        "ru": "История просмотров",
        "en": "History",
        "ua": "Історія переглядів",
        "es": "Historia",
        "zh": "历史",
        "hi": "इतिहास",
        "de": "Geschichte",
    },
    "hist-btn": {
        "ru": "Загрузить историю",
        "en": "Show history",
        "ua": "Завантажити історію",
        "es": "Mostrar la historia",
        "zh": "显示历史",
        "hi": "इतिहास दिखाओ",
        "de": "Zeige die Geschichte",
    },
    "history-btn": {
        "ru": "История",
        "en": "History",
        "ua": "Історія",
        "es": "Historia",
        "zh": "历史",
        "hi": "इतिहास",
        "de": "Geschichte",
    },
    "search-text": {
        "ru": "Поиск",
        "en": "Search",
        "ua": "Пошук",
        "es": "Búsqueda",
        "zh": "搜索",
        "hi": "खोज",
        "de": "Suche",
    },
    "0": {
        "ru": "",
        "en": "",
        "ua": "",
        "es": "",
        "zh": "",
        "hi": "",
        "de": "",
    }
    
}